version: '3.7'

services:
  postgres:
    image: postgres:15
    container_name: eventsync_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eventsync
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - eventsync_network

networks:
  eventsync_network:
    driver: bridge

volumes:
  pgdata:
